import type { ConfigContext, ExpoConfig } from "expo/config";

/**
 * Sous Kit iOS app config.
 *
 * Continuous Native Generation: the `ios/` project is generated by
 * `expo prebuild` (locally or in CI) and is never committed.
 *
 * CI / environment overrides:
 * - SOUSKIT_IOS_BUNDLE_ID    — Apple bundle identifier (must match the
 *   provisioning profile used to sign release builds).
 * - SOUSKIT_IOS_BUILD_NUMBER — CFBundleVersion; unique per TestFlight upload.
 * - SOUSKIT_ASSOCIATED_DOMAIN — host for Universal Links (no scheme), e.g.
 *   recipe-db.joelyoung.dev. Enables https join URLs to open the app.
 * - EXPO_PUBLIC_API_URL    — API base URL baked into the JS bundle
 *   (see src/config.ts for defaults).
 */
const associatedDomain =
  process.env.SOUSKIT_ASSOCIATED_DOMAIN || "recipe-db.joelyoung.dev";

export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  name: "Sous Kit",
  slug: "sous-kit",
  version: "1.0.0",
  orientation: "portrait",
  icon: "./assets/images/icon.png",
  scheme: "souskit",
  userInterfaceStyle: "dark",
  backgroundColor: "#090b09",
  ios: {
    // `||` (not `??`): CI passes unset GitHub vars through as empty strings.
    bundleIdentifier: process.env.SOUSKIT_IOS_BUNDLE_ID || "com.joelyoung.souskit",
    buildNumber: process.env.SOUSKIT_IOS_BUILD_NUMBER || "1",
    supportsTablet: false,
    // Sign in with Apple entitlement (the App ID must have the capability
    // enabled in the Apple Developer portal).
    usesAppleSignIn: true,
    // Universal Links: https://<domain>/join/<token> opens the app when
    // installed; otherwise the web join page handles the invite.
    associatedDomains: [`applinks:${associatedDomain}`],
    config: {
      usesNonExemptEncryption: false,
    },
  },
  web: {
    output: "static",
    favicon: "./assets/images/favicon.png",
  },
  plugins: [
    "expo-router",
    [
      "expo-splash-screen",
      {
        backgroundColor: "#090b09",
        image: "./assets/images/splash-icon.png",
        imageWidth: 120,
      },
    ],
    "expo-secure-store",
    [
      "expo-image-picker",
      {
        photosPermission:
          "Sous Kit uses your photo library so you can pick recipe cover photos.",
        cameraPermission: "Sous Kit uses your camera so you can photograph recipes.",
      },
    ],
    "expo-apple-authentication",
    [
      "expo-local-authentication",
      {
        faceIDPermission: "Sous Kit uses Face ID to unlock the app.",
      },
    ],
  ],
  experiments: {
    typedRoutes: true,
  },
});
